doctrine:
    dbal:
        default_connection: FOO3D
        connections:
            FOO3D:
                url: '%env(resolve:FOO3D)%'
                # IMPORTANT: You MUST configure your db driver and server version,
                # either here or in the DATABASE_URL env var (see .env file)
                driver: 'mysql'
                server_version: '8.0'
                # Only needed for MySQL (ignored otherwise)
                charset: utf8mb4
                default_table_options:
                    collate: utf8mb4_unicode_ci

    orm:
        default_entity_manager: FOO3D
        entity_managers:
            FOO3D:
                connection: FOO3D
                mappings:
                    SYSI:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%\src\Entity\FOO3D'
                        prefix: 'App\Entity\FOO3D'
                        alias: FOO3D

            default:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%\src\Entity\FOO3D'
                        prefix: 'App\Entity\FOO3D'
                        alias: App

#        auto_generate_proxy_classes: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true
#        mappings:


